### ISSUE TITLE
ShoonyaTicker.py updated

### ISSUE THREAD

**Issue by mohit051091** [Tapanhaz/Shoonya-Websocket#4]
Hi

below method needs a change in self.subscribe needs to have an await keyword, sharing older and updated also

Older:

    async def __handle_connection_message(self, msg: dict) -> None:
        if msg["s"] != "OK" and self.__on_error:
            self._loop.create_task(self.__on_error(msg))
            return
        
        if msg["s"] == "OK":
            if self.snapquote_list:
                snapquote_temp = self.snapquote_list[:]
                self.snapquote_list.clear()
                self.subscribe(
                    instrument=snapquote_temp, 
                    feed_type=FeedType.SNAPQUOTE
                    )

            if self.touchline_list:
                touchline_temp = self.touchline_list[:]
                self.touchline_list.clear()
                self.subscribe(
                    instrument=touchline_temp, 
                    feed_type=FeedType.TOUCHLINE
                    )
            self._loop.create_task(self._ws_run_forever())   
            if self.__on_open:
                self._loop.create_task(self.__on_open(msg))
                
                
                
Updated:

    async def __handle_connection_message(self, msg: dict) -> None:
        if msg["s"] != "OK" and self.__on_error:
            self._loop.create_task(self.__on_error(msg))
            return
        
        if msg["s"] == "OK":
            if self.snapquote_list:
                snapquote_temp = self.snapquote_list[:]
                self.snapquote_list.clear()
                await self.subscribe(
                    instrument=snapquote_temp, 
                    feed_type=FeedType.SNAPQUOTE
                    )

            if self.touchline_list:
                touchline_temp = self.touchline_list[:]
                self.touchline_list.clear()
                await self.subscribe(
                    instrument=touchline_temp, 
                    feed_type=FeedType.TOUCHLINE
                    )
            self._loop.create_task(self._ws_run_forever())   
            if self.__on_open:
                self._loop.create_task(self.__on_open(msg))

**Comment by Tapanhaz** [comment]
Thanks for reporting. I updated the code now .. Please check ..
